### ISSUE TITLE
Ввод задачи: уточнить формат даты в поле "Дата начала"

### ISSUE THREAD

**Issue by irvaskova** [vliplianina/team-9b#1]

**Comment by vliplianina** [comment]
Формат ввода данных в поле "Дата начала": дд-мм-гггг
Аналогично для поля "Дата окончания".
Добавлено в [требования](https://github.com/vliplianina/team-9b/blob/master/TrainingTask%20-%20Requirements.md) п. 6 "Форма ввода задачи"
