### ISSUE TITLE
Форма ввода персоны:  уточнить граничные значения для полей: "Фамилия", "Имя" ,"Отчество", "Должность""

### ISSUE THREAD

**Issue by Vshishkar** [vliplianina/team-9b#16]

**Comment by vliplianina** [comment]
Имеется ввиду ограничение по кол-ву символов?

**Comment by Vshishkar** [comment]
Да, имеется в виду ограничение на кол-во символов

**Comment by vliplianina** [comment]
См. [требования](https://github.com/vliplianina/team-9b/blob/master/TrainingTask%20-%20Requirements.md) п.7 "Форма ввода персоны"
