### ISSUE TITLE
Форма ввода персоны: уточнить допустимые значения для полей: "Фамилия" "Имя" "Отчество" "Должность" 

### ISSUE THREAD

**Issue by Vshishkar** [vliplianina/team-9b#17]

**Comment by vliplianina** [comment]
Фамилия:  (допустимые символы: латиница [A-z], кириллица [А-я], цифры [0-9], точка [.], дефис [-], апостроф ['],  пробел;допустимое кол-во символов [1;50])
Имя:  (допустимые символы: латиница [A-z], кириллица [А-я], цифры [0-9], точка [.], дефис [-], апостроф ['], пробел; допустимое кол-во символов [1;50])
Отчество:  (допустимые символы: латиница [A-z], кириллица [А-я], цифры [0-9], точка [.], дефис [-], апостроф ['], пробел; допустимое кол-во символов [0;50])
Должность:  (допустимые символы: латиница [A-z], кириллица [А-я], цифры [0-9], точка [.], дефис [-], апостроф ['], слеш [/], нижнее подчеркивание [ _ ], вопрос [?], пробел; допустимое кол-во символов [1;100])

Уточнения добавлены в т[ребования](https://github.com/vliplianina/team-9b/blob/master/TrainingTask%20-%20Requirements.md) п.7
