### ISSUE TITLE
Форма ввода проекта. Выяснить сколько символов может содержать поле "Сокращённое название"

### ISSUE THREAD

**Issue by artsiom-kisialiou** [vliplianina/team-9b#3]

**Comment by vliplianina** [comment]
В начале заголовка следует указывать название раздела (модуля, подмодуля). В данном случае название раздела - "Форма ввода проекта". Прошу исправить формулировку.

Физическое ограничение для поля "Сокращённое название"  30 символов.
Добавлено в  [требования](https://github.com/vliplianina/team-9b/blob/master/TrainingTask%20-%20Requirements.md) п. 5 "Форма ввода проекта"
