### ISSUE TITLE
Создание проекта. Уточнить, могут ли в полях "Название","Сокращённое название" содержаться специальные символы.

### ISSUE THREAD

**Issue by artsiom-kisialiou** [vliplianina/team-9b#31]

**Comment by vliplianina** [comment]
Могут содержать следующие спец.символы: нижнее подчеркивание [ _ ] , дефис [-], пробел
См.  [требования](https://github.com/vliplianina/team-9b/blob/master/TrainingTask%20-%20Requirements.md) п. 5 Форма ввода проекта
