### ISSUE TITLE
Форма ввода персоны: уточнить, возможно ли однозначно определить режим формы ( Редактирование или Создание новой персоны)

### ISSUE THREAD

**Issue by Vshishkar** [vliplianina/team-9b#37]
Возможный вариант реализации: В зависимости от режима формы менять текст на кнопке: 
- режим создания - "Добавить"
- режим редактирования - "Сохранить\Изменить"

**Comment by vliplianina** [comment]
Заголовок не совпадает с описанием.
Форма создания персоны должна отличаться от формы редактирования названием: "Форма ввода персоны" и "Форма редактирования персоны" соответственно.
