### ISSUE TITLE
Форма ввода персоны: уточнить поведение системы при наличии множества ошибок в форме

### ISSUE THREAD

**Issue by Vshishkar** [vliplianina/team-9b#41]
Уточнить приоритет отображения ошибок. ( ошибки на Допустимые символы и граничные условия)
Уточнить отображаются ли ошибки сразу на все поля ( пример: ошибки сразу в двух полях)

**Comment by vliplianina** [comment]
Сообщения об ошибках должны отображаться одновременно для всех полей, заполненных недопустимыми значениями.
Последовательность валидации: обязательность заполнения, затем допустимые символы. Физическое ограничение соответствует размеру поля.
