### ISSUE TITLE
Форма "Список проектов". Уточнить максимальную ширину полей

### ISSUE THREAD

**Issue by vanmore** [vliplianina/team-9b#44]

**Comment by vliplianina** [comment]
Не является функциональным требованием. Ширина должна соответствовать максимальному кол-ву символов, допустимому для сохранения на форме создания проекта.
См. [требования ](https://github.com/vliplianina/team-9b/blob/master/TrainingTask%20-%20Requirements.md) п.5 "Форма ввода проекта"
