### ISSUE TITLE
Форма ввода персоны: уточнить поведение при команде "Отмена"

### ISSUE THREAD

**Issue by Vshishkar** [vliplianina/team-9b#47]
1. Сохранится ли пользователь в базу?
2. Сохраняются ли данные, введённые в форме при команде Добавить Персону ?

**Comment by vliplianina** [comment]
При выполнении команды "Отмена" происходит переход на форму со списком сотрудников.
1. Не сохранится, т.к. не была выполнена команда "Сохранить" (если команда "сохранить" выполнена, то осуществляется переход на форму со списком сотрудников)
2. Не сохраняются
