### ISSUE TITLE
Ввод задачи: уточнить, что будет, если оставить поля пустыми и сохранить.

### ISSUE THREAD

**Issue by irvaskova** [vliplianina/team-9b#50]

**Comment by vliplianina** [comment]
Если поле обязательно для заполнения, то должно появится сообщение с информацией об обязательности заполнения.
Если поле не обязательно для заполнения, то должна быть возможность сохранить запись с данным значением поля при заполнении других полей формы допустимыми значениями.
Обязательность заполнения см. в [требованиях ](https://github.com/vliplianina/team-9b/blob/master/TrainingTask%20-%20Requirements.md) п.6 "Форма ввода задачи"
