### ISSUE TITLE
Форма “Список проектов”. Уточнить как добавляется новый проект после команды добавить(вверху списка записей, внизу или сортируется) 

### ISSUE THREAD

**Issue by vanmore** [vliplianina/team-9b#54]

**Comment by vliplianina** [comment]
Осуществляется переход к форме добавления проекта, описанной в   [требованиях ](https://github.com/vliplianina/team-9b/blob/master/TrainingTask%20-%20Requirements.md) п.5 "Форма ввода проекта"

**Comment by vliplianina** [comment]
Внизу, т.к. осуществляется сортировка по идентификатору.
