### ISSUE TITLE
Форма “Список сотрудников”. Уточнить требования к полю "Отчество"

### ISSUE THREAD

**Issue by savishchevA** [vliplianina/team-9b#62]
Необходимо уточнить, какие типы значений являются валидными для заполнения (кириллица, латиница, цифры и т.д.), а также уточнить максимальное и минимальное допустимое количество вводимых символов. Необходимо уточнить, является ли поле обязательным для заполнения, доступно ли для редактирования.

**Comment by vliplianina** [comment]
В списке сотрудников должны быть отображены в полном объёме значения, которые допустимы для сохранения на форме создания сотрудника.
См. [требования ](https://github.com/vliplianina/team-9b/blob/master/TrainingTask%20-%20Requirements.md) п.7 "Форма ввода персоны"
