### ISSUE TITLE
Форма “Список сотрудников”. Уточнить требования к полю "Имя"

### ISSUE THREAD

**Issue by savishchevA** [vliplianina/team-9b#64]
Необходимо уточнить, какие типы значений являются валидными для заполнения (кириллица, латиница, цифры и т.д.), а также уточнить максимальное и минимальное допустимое количество вводимых символов. Необходимо уточнить, является ли поле обязательным для заполнения, доступно ли для редактирования.

**Comment by vliplianina** [comment]
См. комментарий к запросу #61
